version: "3.8"
services:
  auth-back:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=api.santiago.maxtelperu.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.santiago.maxtelperu.com
      - LETSENCRYPT_EMAIL=hubeidata@gmail.com
    env_file:
      - .env
    volumes:
      - .:/app                    # Monta el código fuente
      - /app/node_modules         # Preserva node_modules del contenedor
    networks:
      - ruptela_net

networks:
  ruptela_net:
    external: true