services:
  auth-back:
    build:
      context: ./auth-back
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./auth-back:/app
      - /app/node_modules
    env_file:
      - ./auth-back/.env
    depends_on:
      - mongodb

  auth-front:
    build:
      context: ./auth-front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./auth-front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
