version: '3.8'

services:
  nginx-proxy:
    container_name: nginx
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-proxy-net

  letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx
      - DEFAULT_EMAIL=hubeidata@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-proxy-net

  api-ruptela:
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    expose:
      - "5000"
    ports:
      - "6000:6000"
    environment:
      - VIRTUAL_HOST=ruptela.santiago.maxtelperu.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=ruptela.santiago.maxtelperu.com
      - LETSENCRYPT_EMAIL=hubeidata@gmail.com
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    external: true

volumes:
  certs:
  vhostd:
  html:
