version: "3.8"
services:
  api-ruptela:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "5000"
    ports:
      - "6000:6000"
    environment:
      - VIRTUAL_HOST=ws.ruptela.santiago.maxtelperu.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=ws.ruptela.santiago.maxtelperu.com
      - LETSENCRYPT_EMAIL=hubeidata@gmail.com
    networks:
      - ruptela_net
    volumes:
      - .:/app                    # Monta el código fuente
      - /app/node_modules         # Preserva node_modules del contenedor

networks:
  ruptela_net:
    external: true